import React, { useEffect } from 'react';
import { Breadcrumbs } from '../common/Breadcrumbs';
import { updatePageSEO } from '../../utils/seo';
import { ShieldAlert, AlertTriangle } from 'lucide-react';

interface DisclaimerPageProps {
  onNavigateHome: () => void;
}

export const DisclaimerPage: React.FC<DisclaimerPageProps> = ({ onNavigateHome }) => {
  useEffect(() => {
    updatePageSEO({
      title: 'Disclaimer & Educational Planning Notice – Zeta Calculator',
      description:
        'Official disclaimer regarding educational simulations, financial modeling, and non-affiliation with government, banking, or medical institutions.',
      canonicalUrl: typeof window !== 'undefined' ? `${window.location.origin}/disclaimer` : undefined,
    });
  }, []);

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 pb-20">
      <Breadcrumbs items={[{ label: 'Home', onClick: onNavigateHome }, { label: 'Disclaimer', active: true }]} />

      <header className="mt-4 mb-8">
        <span className="text-xs font-bold text-amber-600 uppercase tracking-wider block mb-1">
          Legal &amp; Regulatory Notice
        </span>
        <h1 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">
          Disclaimer &amp; Educational Planning Notice
        </h1>
        <p className="mt-3 text-lg text-slate-600 leading-relaxed font-normal">
          Important disclosures regarding mathematical approximations, financial scenarios, and the scope of Zeta Calculator utilities.
        </p>
      </header>

      <div className="space-y-6 text-slate-700 text-sm sm:text-base leading-relaxed">
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 flex items-start gap-4">
          <ShieldAlert className="w-6 h-6 text-amber-600 shrink-0 mt-0.5" />
          <div className="text-xs text-amber-950 space-y-2">
            <h2 className="text-sm font-bold uppercase tracking-wider text-amber-900">
              Non-Affiliation Disclosure
            </h2>
            <p>
              Zeta Calculator is an independent digital web utility. Zeta Calculator is <strong>NOT</strong> affiliated with,
              endorsed by, or sponsored by any government body, commercial bank, financial institution,
              healthcare system, or certification agency.
            </p>
          </div>
        </div>

        <section className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-xs space-y-4">
          <h2 className="text-xl font-bold text-slate-900">1. Mathematical Simulations Only</h2>
          <p>
            All calculations, estimations, amortization schedules, growth trajectories, and metrics
            generated by Zeta Calculator are deterministic mathematical simulations provided solely for personal
            informational and preliminary educational planning purposes.
          </p>
          <p>
            Real-world figures may differ due to bank loan origination fees, compounding conventions (e.g. 365/360
            day counts), regional sales tax exemptions, material waste factors in construction, fuel vapor losses,
            and individual physiological variations in metabolic formulas.
          </p>
        </section>

        <section className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-xs space-y-4">
          <h2 className="text-xl font-bold text-slate-900">2. No Professional Advice</h2>
          <p>
            The content and tools on Zeta Calculator do not constitute professional financial, tax, legal, architectural,
            engineering, or medical advice:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-xs sm:text-sm text-slate-600">
            <li>
              <strong>Financial &amp; Loans:</strong> Always consult with a licensed mortgage broker, certified financial planner (CFP), or loan officer before executing legally binding loan agreements or investing capital.
            </li>
            <li>
              <strong>Taxation:</strong> Tax brackets, deductions, and exemptions are subject to periodic legislative updates. Verify all tax calculations with a Certified Public Accountant (CPA) or licensed tax advisor.
            </li>
            <li>
              <strong>Health &amp; Fitness:</strong> BMI and TDEE formulas are statistical approximations and do not account for muscle mass density, bone structure, or clinical health conditions. Consult a qualified medical doctor or registered dietitian before starting a restrictive diet or strenuous exercise regimen.
            </li>
            <li>
              <strong>Construction &amp; Civil Work:</strong> Concrete volumes and structural calculations are preliminary estimates. Obtain stamped architectural drawings and engineering inspections prior to pouring foundations or executing structural renovations.
            </li>
          </ul>
        </section>

        <section className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-8 shadow-xs space-y-4">
          <h2 className="text-xl font-bold text-slate-900">3. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, Zeta Calculator, its developers, and contributors
            shall not be held liable for any direct, indirect, incidental, or consequential damages arising
            out of the use or inability to use the calculators, formulas, or informational guides provided
            on this website.
          </p>
        </section>
      </div>
    </div>
  );
};
